CREATE TABLE Users(
ID INT NOT NULL AUTO_INCREMENT,
Email VARCHAR(100) NOT NULL UNIQUE,
Password VARCHAR(50) NOT NULL,
FullName VARCHAR(100),
Phone VARCHAR(20),
ForgotToken VARCHAR(50),
ActiveToken VARCHAR(50),
Status TINYINT,
CreateAt DATETIME,
UpdateAt DATETIME,
PRIMARY KEY(ID)
)

CREATE TABLE LoginToken(
ID INT NOT NULL AUTO_INCRSEMENT,
UserID INT NOT NULL,
Token VARCHAR(50),
Expire DATETIME,
CreateAt DATETIME,
PRIMARY KEY(ID),
CONSTRAINT FK_LoginToken_Users FOREIGN KEY (UserID) REFERENCES Users(ID) 
)